### ISSUE TITLE
not english player name not shown in discord.

### ISSUE THREAD

**Issue by bonobono1234** [Ly-sec/PalBot#11]
Only Named with english user can see at /players command

**Comment by Ly-sec** [comment]
I will try and see if I can find a fix for that later today

**Comment by Ly-sec** [comment]
Please download t

> Only Named with english user can see at /players command

Please download the latest version and try again. If this doesn't fix it, it might be a discord Issue I think.

**Comment by bonobono1234** [comment]
okay but can you add some korean name too?

**Comment by Ly-sec** [comment]
Done :)

Closing this issue since we got a fully reworked bot. Let's see what other issues are going to appear now.
