### ISSUE TITLE
Server is offline, error

### ISSUE THREAD

**Issue by squidmaeki** [Ly-sec/PalBot#12]
My server is online, but why does it still say Server is offline, error: Error: Failed all 1 attempts?

![image](https://github.com/Ly-sec/PalBot/assets/61579866/95714676-e120-4681-b096-38675e5a8948)

**Comment by squidmaeki** [comment]
I entered my ip like this, is that correct?
![image](https://github.com/Ly-sec/PalBot/assets/61579866/8ba7cd15-f5e8-4557-bf86-23eb06121e5f)

**Comment by squidmaeki** [comment]
> > My server is online, but why does it still say Server is offline, error: Error: Failed all 1 attempts?
> > ![image](https://private-user-images.githubusercontent.com/61579866/302101940-95714676-e120-4681-b096-38675e5a8948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTc5ODEsIm5iZiI6MTcwNzA1NzY4MSwicGF0aCI6Ii82MTU3OTg2Ni8zMDIxMDE5NDAtOTU3MTQ2NzYtZTEyMC00NjgxLWIwOTYtMzg2NzVlNWE4OTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE0NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4Yjc1NzY5MjM0MWNkNzRhMzkwOTVkNDQyMGVhOTM2NjMzMDk3NzMzMTNmMjg4OWQ2OWUxMWIxMWE0NDM2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUi-VFUmMBAJeiz9VyUI2eXqbDqwIhgSxIE40D_1854)
> 
> Did you perhaps enter your local IP address and not your public one in the config.json?

I tried entering the local ip and it still shows offline.
![image](https://github.com/Ly-sec/PalBot/assets/61579866/587e35ac-5c7e-4e6b-be5f-82d43d2a057d)

**Comment by Ly-sec** [comment]
Well you shouldn't be using the local IP but the public one.
Can you send normal rcon commands via the bot?

**Comment by squidmaeki** [comment]
> Well you shouldn't be using the local IP but the public one. Can you send normal rcon commands via the bot?

I tried using the command and it came up like the picture. When a moment has passed It's like picture 2.

![image](https://github.com/Ly-sec/PalBot/assets/61579866/a588a6f8-1fb0-4dec-bf94-61a86a06c5c2)
![image](https://github.com/Ly-sec/PalBot/assets/61579866/48ec67d7-2b90-4df8-8fee-46397f3d7c7d)

**Comment by squidmaeki** [comment]
I can connect through the server tool but palbot can't.
![image](https://github.com/Ly-sec/PalBot/assets/61579866/d98fab4c-c6af-4abe-9642-d5ca0593d8b4)

**Comment by Ly-sec** [comment]
> I can connect through the server tool but palbot can't.
> ![image](https://github.com/Ly-sec/PalBot/assets/61579866/d98fab4c-c6af-4abe-9642-d5ca0593d8b4)
> 

That's indeed very weird, I'll try and see what's going on tomorrow. It's quite late already :/

**Comment by squidmaeki** [comment]
I can send rcon broadcast to the server but it still says Server is offline, error: Error: Failed all 1 attempts

![image](https://github.com/Ly-sec/PalBot/assets/61579866/2a77cc4d-5177-42d6-b9eb-5f37d480aecb)

**Comment by squidmaeki** [comment]
Is there any part that I did wrong?

**Comment by Ly-sec** [comment]
I don't really see anything that you did wrong, however I just checked myself and it works totally fine, same for other people 🤔

**Comment by squidmaeki** [comment]
The whitelist system works but is very slow to attract players who don't have the whitelist

![image](https://github.com/Ly-sec/PalBot/assets/61579866/60d0a49a-bb18-4598-9dac-008e3828b778)

**Comment by squidmaeki** [comment]
> I don't really see anything that you did wrong, however I just checked myself and it works totally fine, same for other people 🤔

Is the port I opened 8211 and 25575 correct or do I need to forward additional ports?

**Comment by Ly-sec** [comment]
> > I don't really see anything that you did wrong, however I just checked myself and it works totally fine, same for other people 🤔
> 
> Is the port I opened 8211 and 25575 correct or do I need to forward additional ports?

In theroy there are these 3 ports: 8211, 25575,27015
Not sure if 27015 would do anything for you though. Could be worth a try however.

**Comment by squidmaeki** [comment]
> In theroy there are these 3 ports: 8211, 25575,27015 Not sure if 27015 would do anything for you though. Could be worth a try however.

I forwarded all ports and inbound ports and it still shows Server is offline, error: Error: Failed all 1 attempts.

**Comment by squidmaeki** [comment]
Everything works fine except the Player count check which cannot be checked.

**Comment by kvcruzat** [comment]
> Everything works fine except the Player count check which cannot be checked.

Just ran across the same issue. It turned out to be because of the server not being a community server. had EpicApp=PalServer removed in the command line argument because read that it helps with performance. Gamedig cant query the server without it.

**Comment by Ly-sec** [comment]
"Should" be fixed now, if not please open up another issue!

Closing this issue since we got a fully reworked bot. Let's see what other issues are going to appear now.
