### ISSUE TITLE
First connect player not shown.

### ISSUE THREAD

**Issue by bonobono1234** [Ly-sec/PalBot#15]
if rcon api say {"results":[{"username":"roro","playeruid":"1393838635","steamid":"76561198987923519"},{"username":"gotak","playeruid":"3244787420","steamid":"76561198073427014"},{"username":"Dyna_Styx","playeruid":"1941128631","steamid":"76561199631163946"}]}
roro is not shown in player list

**Comment by Ly-sec** [comment]
I'll check that later today, thanks for letting me know

**Comment by kvcruzat** [comment]
> I'll check that later today, thanks for letting me know
 
rcon showplayers responds with the first player's name on the same line as the headers. your code splits by line breaks and omits the first line. probably best to just do string replace of the headers first then split with line breaks and remove the omission of the first line.

**Comment by Ly-sec** [comment]
> > I'll check that later today, thanks for letting me know
> 
> rcon showplayers responds with the first player's name on the same line as the headers. your code splits by line breaks and omits the first line. probably best to just do string replace of the headers first then split with line breaks and remove the omission of the first line.

Yeah that's what I'm doing soon too, see https://github.com/Ly-sec/PalBot/discussions/16
The whole bot is rather messy so might as well do it correct this time :).

**Comment by bonobono1234** [comment]
Also, Can you add Korean name is Possible to show? :)

**Comment by bonobono1234** [comment]
> > > I'll check that later today, thanks for letting me know
> > 
> > 
> > rcon showplayers responds with the first player's name on the same line as the headers. your code splits by line breaks and omits the first line. probably best to just do string replace of the headers first then split with line breaks and remove the omission of the first line.
> 
> Yeah that's what I'm doing soon too, see #16 The whole bot is rather messy so might as well do it correct this time :).


Also, Can you add Korean name is Possible to show? :)

**Comment by Ly-sec** [comment]
> > > > I'll check that later today, thanks for letting me know
> > > 
> > > 
> > > rcon showplayers responds with the first player's name on the same line as the headers. your code splits by line breaks and omits the first line. probably best to just do string replace of the headers first then split with line breaks and remove the omission of the first line.
> > 
> > Yeah that's what I'm doing soon too, see #16 The whole bot is rather messy so might as well do it correct this time :).
> 
> 
> Also, Can you add Korean name is Possible to show? :)

100% if you look at my discussion then you'll know :) already fixed that
