### ISSUE TITLE
Error: Used disallowed intents

### ISSUE THREAD

**Issue by sosacdiego** [Ly-sec/PalBot#20]
When running the bot using the `node .` command, I receive the following error:

```
throw new Error("Used disallowed intents");
      ^

Error: Used disallowed intents
```

I've given the bot basically every permission in my server (except for Admin), do you know what else i could try?

NOTE: I solved this by going into the Bot Application -> Settings -> Bot -> Privileged Gateway Intents and toggling on all of the intents. Posting this anyway in case someone else runs into this issue! Would be helpful to have in the README

**Comment by Ly-sec** [comment]
Oh I totally forgot to put that part into the readme, going to add it asap!

**Comment by Ly-sec** [comment]
Added, closing the issue now :). Thanks again!
