### ISSUE TITLE
Commands that dont work

### ISSUE THREAD

**Issue by xblitz151** [Ly-sec/PalBot#23]
Feed back for all commands on Linux. Half of them dont work correctly.
I checked all permissions/roles/channels in my config, checked the bots App Integrations.
Let me know if im missing something for the setup of the bot?? 

/Broadcast (Bot returns saying No permissions)
/Players (works but the return from bot mixes players info)
/reload commands (Bot returns This command is only available to the developer)
/Reload events (This command is only available to the developer.)
/Save (No permissions)
/Server (works good, pulls all the info and displays)
/Whitelist Enalbe (works)
/Whitelist Disable (works)
/Whitelist-edit add (Bot returns saying You did not set up your config.json correctly!"
/whitelist-edit remove (You did not set up your config.json correctly!)
/shutdown (No permissions)

**Comment by xblitz151** [comment]
![players](https://github.com/Ly-sec/PalBot/assets/20955479/d3f88be1-9456-4b9b-8966-04c5dbcec50c)

Currently there is 3 players in the server (my self and 2 others)
/server shows wrong player count
/players only shows 1 and broken

**Comment by Ly-sec** [comment]
Sorry for the very late reply!
Not entirely sure what's going on there since it seems to be working fine for me :/

**Comment by xblitz151** [comment]
> Sorry for the very late reply! Not entirely sure what's going on there since it seems to be working fine for me :/

Its ok. So you don't have any idea why? I've tried on both Linux and Windows. If you have a discord and wanna try trouble shooting with me lmk

**Comment by Ly-sec** [comment]
Uhm it does seem like there is something going on with your rcon connection.
What I noticed, restarting the palworld server helps sometimes

**Comment by MattyCanny** [comment]
Hello!

In the screenshot xblitz151 has posted demonstrating the players command, you will see that it is not handing the data RCON is returning property. 

However you line that handles the list of users is not separating the next line. IN xblitz151's screenshot the name of the second player is at the end of the first players Steam ID.

I am also having this issue.

**Comment by Ly-sec** [comment]
> Hello!
> 
> In the screenshot xblitz151 has posted demonstrating the players command, you will see that it is not handing the data RCON is returning property.
> 
> The code line that handles the list of users is not separating the next line. IN xblitz151's screenshot the name of the second player is at the end of the first players Steam ID.
> 
> I am also having this issue.

I'll double check that tomorrow, it's quite late already :/

**Comment by Ly-sec** [comment]
@xblitz151 @MattyCanny https://github.com/Ly-sec/PalBot/commit/94b84e7a7e7f060aa13c1900c2b23f51d0050a0e this (hopefully) fixes that issue. I sadly can't properly test it since I'm the only person on my server. Gonna upload a new release in a second too.

**Comment by Ly-sec** [comment]
> > @xblitz151 @MattyCanny [94b84e7](https://github.com/Ly-sec/PalBot/commit/94b84e7a7e7f060aa13c1900c2b23f51d0050a0e) this (hopefully) fixes that issue. I sadly can't properly test it since I'm the only person on my server. Gonna upload a new release in a second too.
> 
> Facing the same error despite using the latest version that's supposed to fix the /players command. There are currently 9+ players at the time of taking the screenshot ![image](https://private-user-images.githubusercontent.com/22678541/304040335-2336b435-0965-4c59-b550-b63d7f0493cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzkzMjQsIm5iZiI6MTcwNzczOTAyNCwicGF0aCI6Ii8yMjY3ODU0MS8zMDQwNDAzMzUtMjMzNmI0MzUtMDk2NS00YzU5LWI1NTAtYjYzZDdmMDQ5M2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDExNTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZjI0OTE2OWNjZWViNjgyNjg2ZWNmNTBhOTNkM2ZmZWI3MGFlNTEzM2M0Y2U5OWQ1MGI3NzA2YWVlMmQ5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2WHH7E3C0H1xVdhzCaPUNrTr_x65z9Pgck71gmilLM)

Hey, I'm still unsure on why that's happening. Would you mind adding me on discord (Lysec) so we can test it easier since I don't have many active people on my server lmao?

**Comment by Ly-sec** [comment]
https://github.com/Ly-sec/PalBot/releases/tag/release-0.0.7 Fixed
