### ISSUE TITLE
whitelist check not work

### ISSUE THREAD

**Issue by hAKIZOR** [Ly-sec/PalBot#6]
after i wait intervalId time got error in console:
"Error: error: Connection error"
i think the problem is here "await client.connect();"

**Comment by Ly-sec** [comment]
> after i wait intervalId time got error in console: "Error: error: Connection error" i think the problem is here "await client.connect();"

Tried it just now again and I couldn't seem to replicate the issue. Do you have any further information?

**Comment by Ly-sec** [comment]
> mmh add me on discord if u want haki6523 and i can show u in screen share

I'll be home in an hour or so, going to add you then :)

**Comment by Ly-sec** [comment]
> mmh add me on discord if u want haki6523 and i can show u in screen share

Just added you, whenever you're awake, please send me any more infos you got. If we are online at the same time please just call me :) I'm pretty sure we can fix it

**Comment by Ly-sec** [comment]
Sorry for the very late reply, I pushed another update today, this should fix all the whitelist issues.

**Comment by Ly-sec** [comment]
Been fixed for a while :)

Closing this issue since we got a fully reworked bot. Let's see what other issues are going to appear now.
