### ISSUE TITLE
Bot is showing only the first 10 digits of the steam ID, resulting in a kick caused by a mistmatch

### ISSUE THREAD

**Issue by AWL-Gaming** [Ly-sec/PalBot#7]
At times the bot will show only the 1st 10 digits of the online player's Steam ID, resulting in them being kicked. Moreover, it'll also add 2 digits at the end of the Steam ID. Both issues will make the ID appear as mismatched while it's not. A temporary workaround is to copy the entire whitelist, keep the first 10 digits and paste them under the full IDs which is not practical.
The picture below explains the issue:
![image](https://github.com/Ly-sec/PalBot/assets/22678541/9acf7ac1-d5bc-4718-b355-a2554af8a264)

**Comment by AWL-Gaming** [comment]
Last two digits added by the bot are only 10 or 13 from what we've obtained so far:
![image](https://github.com/Ly-sec/PalBot/assets/22678541/12be41a9-8dab-4a1a-a427-42ab7b8e1a16)

**Comment by Ly-sec** [comment]
> Last two digits added by the bot are only 10 or 13 from what we've obtained so far: ![image](https://private-user-images.githubusercontent.com/22678541/301325495-12be41a9-8dab-4a1a-a427-42ab7b8e1a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzk3NTgsIm5iZiI6MTcwNjczOTQ1OCwicGF0aCI6Ii8yMjY3ODU0MS8zMDEzMjU0OTUtMTJiZTQxYTktOGRhYi00YTFhLWE0MjctNDJhYjdiOGUxYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIyMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGM1ZTdmZmM1YmMxZWYwYzM0NGZkNjJlOTdkNTljZjU2YjBkMWY2ZGY3YTgzMWNlYTE3Nzk4ODE0OGExNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwcuSVB2IwZtoeKNwDfc0P93xeDSMxnhnA0He069X8A)

I'll see if I can replicate that, probably going to be a bit hard since I don't have access to a server with tons of people :/

**Comment by Ly-sec** [comment]
> Last two digits added by the bot are only 10 or 13 from what we've obtained so far: ![image](https://private-user-images.githubusercontent.com/22678541/301325495-12be41a9-8dab-4a1a-a427-42ab7b8e1a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzk3NTgsIm5iZiI6MTcwNjczOTQ1OCwicGF0aCI6Ii8yMjY3ODU0MS8zMDEzMjU0OTUtMTJiZTQxYTktOGRhYi00YTFhLWE0MjctNDJhYjdiOGUxYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIyMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGM1ZTdmZmM1YmMxZWYwYzM0NGZkNjJlOTdkNTljZjU2YjBkMWY2ZGY3YTgzMWNlYTE3Nzk4ODE0OGExNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwcuSVB2IwZtoeKNwDfc0P93xeDSMxnhnA0He069X8A)

I'll see if I can replicate it but I sadly don't have a server with tons of people (which I assume might be why this is even happening...

**Comment by AWL-Gaming** [comment]
> > Last two digits added by the bot are only 10 or 13 from what we've obtained so far: ![image](https://private-user-images.githubusercontent.com/22678541/301325495-12be41a9-8dab-4a1a-a427-42ab7b8e1a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzk3NTgsIm5iZiI6MTcwNjczOTQ1OCwicGF0aCI6Ii8yMjY3ODU0MS8zMDEzMjU0OTUtMTJiZTQxYTktOGRhYi00YTFhLWE0MjctNDJhYjdiOGUxYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIyMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGM1ZTdmZmM1YmMxZWYwYzM0NGZkNjJlOTdkNTljZjU2YjBkMWY2ZGY3YTgzMWNlYTE3Nzk4ODE0OGExNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwcuSVB2IwZtoeKNwDfc0P93xeDSMxnhnA0He069X8A)
> 
> I'll see if I can replicate it but I sadly don't have a server with tons of people (which I assume might be why this is even happening...

Original whitelist contains about 70 IDs, which is now doubled because of the 10-digit issue's workaround.

**Comment by Ly-sec** [comment]
> > > Last two digits added by the bot are only 10 or 13 from what we've obtained so far: ![image](https://private-user-images.githubusercontent.com/22678541/301325495-12be41a9-8dab-4a1a-a427-42ab7b8e1a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzk3NTgsIm5iZiI6MTcwNjczOTQ1OCwicGF0aCI6Ii8yMjY3ODU0MS8zMDEzMjU0OTUtMTJiZTQxYTktOGRhYi00YTFhLWE0MjctNDJhYjdiOGUxYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIyMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGM1ZTdmZmM1YmMxZWYwYzM0NGZkNjJlOTdkNTljZjU2YjBkMWY2ZGY3YTgzMWNlYTE3Nzk4ODE0OGExNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwcuSVB2IwZtoeKNwDfc0P93xeDSMxnhnA0He069X8A)
> > 
> > 
> > I'll see if I can replicate it but I sadly don't have a server with tons of people (which I assume might be why this is even happening...
> 
> Original whitelist contains about 70 IDs, which is now doubled because of the 10-digit issue's workaround.

Gonna check tomorrow if I can fix it. The more I think about it, I think I had a similar issue with the ids just being scuffed like that. We'll see though.

**Comment by AWL-Gaming** [comment]
> > > > Last two digits added by the bot are only 10 or 13 from what we've obtained so far: ![image](https://private-user-images.githubusercontent.com/22678541/301325495-12be41a9-8dab-4a1a-a427-42ab7b8e1a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzk3NTgsIm5iZiI6MTcwNjczOTQ1OCwicGF0aCI6Ii8yMjY3ODU0MS8zMDEzMjU0OTUtMTJiZTQxYTktOGRhYi00YTFhLWE0MjctNDJhYjdiOGUxYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIyMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGM1ZTdmZmM1YmMxZWYwYzM0NGZkNjJlOTdkNTljZjU2YjBkMWY2ZGY3YTgzMWNlYTE3Nzk4ODE0OGExNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwcuSVB2IwZtoeKNwDfc0P93xeDSMxnhnA0He069X8A)
> > > 
> > > 
> > > I'll see if I can replicate it but I sadly don't have a server with tons of people (which I assume might be why this is even happening...
> > 
> > 
> > Original whitelist contains about 70 IDs, which is now doubled because of the 10-digit issue's workaround.
> 
> Gonna check tomorrow if I can fix it. The more I think about it, I think I had a similar issue with the ids just being scuffed like that. We'll see though.

Thank you, keep me updated when you can. Had to pause the whitelist for now since it was kicking the legit whitelisted players as well.

**Comment by Ly-sec** [comment]
> I had a similar problem with big numbers. As I remember, I manage them as strings and not as numbers. Node have a length limit for digits.

Oh this is actually a good call, let's try that too. Working on a different fix right now but I'll turn the ids into strings too, just in case.

**Comment by Ly-sec** [comment]
@AWL-Gaming I pushed a new update, please try this and see if it works better now :).

**Comment by AWL-Gaming** [comment]
![image](https://github.com/Ly-sec/PalBot/assets/22678541/619d8c32-69ac-44ea-af92-c01c49fb6fb0)
Working perfectly fine now! Tried it on my own ID as well, un-whitelisting then relisting and it didn't touch the other IDs nor did it switch the numbers. Thank you for the quick update and fix!
