### ISSUE TITLE
Bot crashing with Error: Error: Connection error

### ISSUE THREAD

**Issue by alex010x** [Ly-sec/PalBot#8]
I got crash every few minutes since last Palworld update (1.4.0). 
Was working fine before that.

The only output I'm able to see is: Error: Error: Connection error

**Comment by Ly-sec** [comment]
Please double check that your rcon password is still set.
Just updated my server and everything seems to be working fine.

**Comment by alex010x** [comment]
Password is correctly set.
It works for a while, then suddenly crash with that error, which I guess is somehow related to the rcon connect failure

**Comment by Ly-sec** [comment]
So I assume you're using the whitelist feature, right?
Please download the newest version and see if that fixes it.

**Comment by alex010x** [comment]
Yes, whitelist feature.
I tried the new version, but error is still ongoing.

**Comment by Ly-sec** [comment]
Can you try disabling the whitelist and try to use other rcon commands (players, broadcast etc)? I would love to know if you also get errors with that.

**Comment by alex010x** [comment]
Yea.
![image](https://github.com/Ly-sec/PalBot/assets/34274946/f224b1e5-f6ea-4817-b8b8-88da20a900f4)

**Comment by Ly-sec** [comment]
This is very odd since it seems like most people don't have an issue with that. 
Are you connecting through the rcon port (25575), are you using the correct IP address?
Did you setup the password in your palworld server config?

**Comment by Ly-sec** [comment]
I pushed an attempt at fixing this issue, since I didn't encounter it yet I can only guess. It started happening since the status feature is in place so please download / pull the newest version and see if that helps.

**Comment by alex010x** [comment]
Same error from here: https://github.com/Ly-sec/PalBot/issues/9#issue-2113074829 ?

Still got the same errors as before, with the new version. So far, `/server` seems to be the only command working

**Comment by Ly-sec** [comment]
> Same error from here: [#9 (comment)](https://github.com/Ly-sec/PalBot/issues/9#issue-2113074829) ?
> 
> Still got the same errors as before, with the new version. So far, `/server` seems to be the only command working

I really don't get it, it's working totally fine for me and also others. Wanna add me on discord (Lysec) real quick? might be easier to troubleshoot

**Comment by Ly-sec** [comment]
Should be fixed now!

Closing this issue since we got a fully reworked bot. Let's see what other issues are going to appear now.
