### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by GameAreaCZ** [Ly-sec/PalBot#9]
Application is not responding. After a while this error:

Error connecting to Rcon: Error: Connection error
    at Socket.<anonymous> (/home/spravce/boti/Palworld/node_modules/minecraft-rcon-client/lib/index.js:29:68)
    at Object.onceWrapper (node:events:633:26)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Connection error
    at Socket.<anonymous> (/home/spravce/boti/Palworld/node_modules/minecraft-rcon-client/lib/index.js:29:68)
    at Object.onceWrapper (node:events:633:26)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.11.0

**Comment by GameAreaCZ** [comment]
The /server is working, but it is reporting wrong player number (same in the bot status).

**Comment by GameAreaCZ** [comment]
at handleErrors (/home/spravce/boti/Palworld/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/spravce/boti/Palworld/node_modules/@discordjs/rest/dist/index.js:736:23)
    at async REST.request (/home/spravce/boti/Palworld/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async ChatInputCommandInteraction.reply (/home/spravce/boti/Palworld/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async Object.execute (/home/spravce/boti/Palworld/Commands/Public/Info/players.js:52:13) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: 'An error occurred while fetching player list.',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',

**Comment by GameAreaCZ** [comment]
I tried change the IP to my internal one (ofc it said, that server is offline), but the commands are working (ofc the /server do not), but the /players is reporting the correct count of players, but the bot status isn't.

Why is the bot status not fetching same logic as the /players command? It looks like the /players command is even faster with the updates.

**Comment by Ly-sec** [comment]
> I tried change the IP to my internal one (ofc it said, that server is offline), but the commands are working (ofc the /server do not), but the /players is reporting the correct count of players, but the bot status isn't.
> 
> Why is the bot status not fetching same logic as the /players command? It looks like the /players command is even faster with the updates.

It is doing the same thing as the players command, however it seems like the status feature is the issue right now. I removed it for now until I find a proper fix, please download the latest release :)

**Comment by Ly-sec** [comment]
Oh also about the /server command:
I sadly can not do much about it, that's up to battlemetrics to fix :/

**Comment by GameAreaCZ** [comment]
Oh thank you :-) ye I will wait, because the status is the best feature for me :-) I like having this status message in my Discord server for all my community servers. Ofc the commands are good too, but the reliable bot status is the main thing for me. Thank you for your work.

**Comment by Ly-sec** [comment]
> Oh thank you :-) ye I will wait, because the status is the best feature for me :-) I like having this status message in my Discord server for all my community servers. Ofc the commands are good too, but the reliable bot status is the main thing for me. Thank you for your work.

I know a friend of mine got it to work, I'll ask him later/tomorrow and see how he did it, then I'll try to implement it again :)

**Comment by Ly-sec** [comment]
It **_should_** be fixed with the newest release :).

**Comment by GameAreaCZ** [comment]
Will try, ty.

**Comment by GameAreaCZ** [comment]
Why is the bot status do not work when internal IP is set? It cannot get it from the same logic like /players? I guess the /players is getting it with rcon command ShowPlayers. So cannot the status bot getting it from there also?

I really do not want to open a rcon port for public.

**Comment by Ly-sec** [comment]
> Why is the bot status do not work when internal IP is set? It cannot get it from the same logic like /players? I guess the /players is getting it with rcon command ShowPlayers. So cannot the status bot getting it from there also?
> 
> I really do not want to open a rcon port for public.

It's not rcon, it's using the ip + your normal port, not rcon :).
Since I don't have access to most of these informations, I'm relying on battlemetrics for that, that's why the internal IP wont work.

**Comment by Ly-sec** [comment]
> So the online players is taking data from battlemetrics? Oh. Isn't that be so slow to update? I thought it takes from the rcon command ShowPlayers and just count rows or something like the /players do.
> 
> Then you can set the timer for do the command and take that info from the result to update bot status?

Good call, I'm stupid xD gonna rework that part somewhere this weekend

**Comment by GameAreaCZ** [comment]
Nice! Thank you! I think in that way it will be so much more faster/reliable to have nice bot status. And if you can do the configurable status update interval. It will be so nice.

**Comment by Ly-sec** [comment]
> Nice! Thank you! I think in that way it will be so much more faster/reliable to have nice bot status. And if you can do the configurable status update interval. It will be so nice.

Probably going to work on that on sunday, quite busy this weekend sadly.

**Comment by GameAreaCZ** [comment]
Ye it's ok :-) no need to rush. Ty for your work.

**Comment by Ly-sec** [comment]
Everything should work now, adding the interval command soonish :)

Closing this issue since we got a fully reworked bot. Let's see what other issues are going to appear now.
